
package com.learnwebservices.services.hello;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "HelloEndpointService", targetNamespace = "http://hello.services.learnwebservices.com/", wsdlLocation = "http://www.learnwebservices.com/services/hello?WSDL")
public class HelloEndpointService
        extends Service {

    private final static URL SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEHELLOENDPOINTSERVICE_EXCEPTION;
    private final static QName SIMPLEHELLOENDPOINTSERVICE_QNAME = new QName("http://learnwebservices.com/services/hello", "HelloEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.learnwebservices.com/services/hello?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION = url;
        SIMPLEHELLOENDPOINTSERVICE_EXCEPTION = e;
    }

    public HelloEndpointService() {
        super(__getWsdlLocation(), SIMPLEHELLOENDPOINTSERVICE_QNAME);
    }

    public HelloEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEHELLOENDPOINTSERVICE_QNAME, features);
    }

    public HelloEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEHELLOENDPOINTSERVICE_QNAME);
    }

    public HelloEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEHELLOENDPOINTSERVICE_QNAME, features);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort() {
        return super.getPort(new QName("http://learnwebservices.com/services/hello", "HelloEndpointPort"), HelloEndpoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.services.learnwebservices.com/", "SimpleHelloEndpointPort"), HelloEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEHELLOENDPOINTSERVICE_EXCEPTION != null) {
            throw SIMPLEHELLOENDPOINTSERVICE_EXCEPTION;
        }
        return SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION;
    }

}
