
package com.learnwebservices.services.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "HelloEndpoint", targetNamespace = "http://learnwebservices.com/services/hello")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface HelloEndpoint {


    /**
     * @param helloRequest
     * @return returns com.learnwebservices.services.hello.HelloResponse
     */
    @WebMethod(operationName = "SayHello")
    @WebResult(name = "HelloResponse", targetNamespace = "http://learnwebservices.com/services/hello")
    @RequestWrapper(localName = "SayHello", targetNamespace = "http://learnwebservices.com/services/hello", className = "com.learnwebservices.services.hello.SayHello")
    @ResponseWrapper(localName = "SayHelloResponse", targetNamespace = "http://learnwebservices.com/services/hello", className = "com.learnwebservices.services.hello.SayHelloResponse")
    public HelloResponse sayHello(
            @WebParam(name = "HelloRequest", targetNamespace = "http://learnwebservices.com/services/hello")
                    HelloRequest helloRequest);

}
