
package com.learnwebservices.services.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleHelloEndpointService", targetNamespace = "http://hello.services.learnwebservices.com/", wsdlLocation = "http://www.learnwebservices.com/services/hello?WSDL")
public class SimpleHelloEndpointService
    extends Service
{

    private final static URL SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEHELLOENDPOINTSERVICE_EXCEPTION;
    private final static QName SIMPLEHELLOENDPOINTSERVICE_QNAME = new QName("http://hello.services.learnwebservices.com/", "SimpleHelloEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.learnwebservices.com/services/hello?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION = url;
        SIMPLEHELLOENDPOINTSERVICE_EXCEPTION = e;
    }

    public SimpleHelloEndpointService() {
        super(__getWsdlLocation(), SIMPLEHELLOENDPOINTSERVICE_QNAME);
    }

    public SimpleHelloEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEHELLOENDPOINTSERVICE_QNAME, features);
    }

    public SimpleHelloEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEHELLOENDPOINTSERVICE_QNAME);
    }

    public SimpleHelloEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEHELLOENDPOINTSERVICE_QNAME, features);
    }

    public SimpleHelloEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleHelloEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "SimpleHelloEndpointPort")
    public HelloEndpoint getSimpleHelloEndpointPort() {
        return super.getPort(new QName("http://hello.services.learnwebservices.com/", "SimpleHelloEndpointPort"), HelloEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "SimpleHelloEndpointPort")
    public HelloEndpoint getSimpleHelloEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello.services.learnwebservices.com/", "SimpleHelloEndpointPort"), HelloEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEHELLOENDPOINTSERVICE_EXCEPTION!= null) {
            throw SIMPLEHELLOENDPOINTSERVICE_EXCEPTION;
        }
        return SIMPLEHELLOENDPOINTSERVICE_WSDL_LOCATION;
    }

}
