
package helloWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloEndpointService", targetNamespace = "http://learnwebservices.com/services/hello", wsdlLocation = "file:/D:/CODE%20GIT/ws-client/src/wsdl/hello.wsdl")
public class HelloEndpointService
    extends Service
{

    private final static URL HELLOENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOENDPOINTSERVICE_EXCEPTION;
    private final static QName HELLOENDPOINTSERVICE_QNAME = new QName("http://learnwebservices.com/services/hello", "HelloEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CODE%20GIT/ws-client/src/wsdl/hello.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOENDPOINTSERVICE_WSDL_LOCATION = url;
        HELLOENDPOINTSERVICE_EXCEPTION = e;
    }

    public HelloEndpointService() {
        super(__getWsdlLocation(), HELLOENDPOINTSERVICE_QNAME);
    }

    public HelloEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOENDPOINTSERVICE_QNAME, features);
    }

    public HelloEndpointService(URL wsdlLocation) {
        super(wsdlLocation, HELLOENDPOINTSERVICE_QNAME);
    }

    public HelloEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOENDPOINTSERVICE_QNAME, features);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort() {
        return super.getPort(new QName("http://learnwebservices.com/services/hello", "HelloEndpointPort"), HelloEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://learnwebservices.com/services/hello", "HelloEndpointPort"), HelloEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOENDPOINTSERVICE_EXCEPTION!= null) {
            throw HELLOENDPOINTSERVICE_EXCEPTION;
        }
        return HELLOENDPOINTSERVICE_WSDL_LOCATION;
    }

}
